name = "openboot"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "openboot.dev"
custom_domain = true

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "openboot"
database_id = "6faf0c13-b182-4dca-bf13-ec346d085960"
migrations_dir = "migrations"

[vars]
APP_URL = "https://openboot.dev"
